export const industries = [
  { name: 'Accountancy', description: 'Accountancy' },
  { name: 'Air Transport', description: 'Air Transport' },
  { name: 'Aerospace', description: 'Aerospace' },
  {
    name: 'Biopharmaceuticals Manufacturing',
    description: 'Biopharmaceuticals Manufacturing',
  },
  { name: 'Built Environment', description: 'Built Environment' },
  { name: 'Design', description: 'Design' },
  { name: 'Early Childhood', description: 'Early Childhood' },
  { name: 'Electronics', description: 'Electronics' },
  { name: 'Energy And Chemicals', description: 'Energy And Chemicals' },
  { name: 'Energy And Power', description: 'Energy And Power' },
  { name: 'Engineering Services', description: 'Engineering Services' },
  {
    name: 'Environmental Services',
    description: 'Environmental Services',
  },
  { name: 'Financial Services', description: 'Financial Services' },
  { name: 'Food Manufacturing', description: 'Food Manufacturing' },
  { name: 'Food Services', description: 'Food Services' },
  { name: 'Healthcare', description: 'Healthcare' },
  {
    name: 'Hotel & Accommodation Services',
    description: 'Hotel & Accommodation Services',
  },
  { name: 'Human Resource', description: 'Human Resource' },
  { name: 'Infocomm Technology', description: 'Infocomm Technology' },
  {
    name: 'Intellectual Property',
    description: 'Intellectual Property',
  },
  { name: 'Landscape', description: 'Landscape' },
  { name: 'Logistics', description: 'Logistics' },
  { name: 'Marine And Offshore', description: 'Marine And Offshore' },
  { name: 'Media', description: 'Media' },
  {
    name: 'Precision Engineering',
    description: 'Precision Engineering',
  },
  { name: 'Public Transport', description: 'Public Transport' },
  { name: 'Retail', description: 'Retail' },
  { name: 'Sea Transport', description: 'Sea Transport' },
  { name: 'Security', description: 'Security' },
  { name: 'Social Service', description: 'Social Service' },
  { name: 'Tourism', description: 'Tourism' },
  {
    name: 'Training And Adult Education',
    description: 'Training And Adult Education',
  },
  { name: 'Wholesale Trade', description: 'Wholesale Trade' },
  {
    name: 'Workplace Safety And Health',
    description: 'Workplace Safety And Health',
  },
];
